import os
import logging
import requests
import feedparser
from datetime import datetime
from urllib.parse import quote

logger = logging.getLogger(__name__)

# AI_PROVIDER selects which model does the writing: "gemini" (Google, free
# tier available, no card needed — good for testing) or "anthropic" (Claude,
# paid). Switching later is just changing this one env var, no code changes.
AI_PROVIDER = os.environ.get("AI_PROVIDER", "gemini").lower()

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5")
ANTHROPIC_URL = "https://api.anthropic.com/v1/messages"

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")  # free-tier eligible

BULL_PATTERNS = ["Hammer", "Bullish Engulfing", "Morning Star", "Bullish Marubozu", "Three White Soldiers"]
BEAR_PATTERNS = ["Shooting Star", "Bearish Engulfing", "Evening Star", "Bearish Marubozu", "Three Black Crows"]

LANG_NAMES = {'fa': 'Persian (Farsi)', 'en': 'English', 'ru': 'Russian'}

TITLES = {
    'fa': '🤖 تحلیل هوش مصنوعی (تکنیکال + اخبار)',
    'en': '🤖 AI Analysis (Technical + News)',
    'ru': '🤖 ИИ-анализ (технический + новости)',
}

DISCLAIMERS = {
    'fa': '⚠️ این تحلیل توسط هوش مصنوعی و صرفاً جهت اطلاع‌رسانی تولید شده و توصیه مالی نیست. قبل از هر تصمیمی خودتان تحقیق کنید (DYOR).',
    'en': '⚠️ This analysis was generated by AI for informational purposes only and is not financial advice. Always DYOR before making decisions.',
    'ru': '⚠️ Этот анализ создан ИИ исключительно в информационных целях и не является финансовым советом. Всегда проводите собственное исследование (DYOR).',
}

NO_NEWS = {
    'fa': 'خبر مرتبط تازه‌ای برای این کوین پیدا نشد.',
    'en': 'No fresh coin-specific news found.',
    'ru': 'Свежих новостей по этой монете не найдено.',
}

REQUIRED_KEY_VAR = "GEMINI_API_KEY" if AI_PROVIDER != "anthropic" else "ANTHROPIC_API_KEY"

NO_KEY_ERROR = {
    'fa': f'کلید API هوش مصنوعی تنظیم نشده ({REQUIRED_KEY_VAR} را در تنظیمات Railway اضافه کنید).',
    'en': f'AI API key is not configured (set {REQUIRED_KEY_VAR} in Railway variables).',
    'ru': f'API-ключ ИИ не настроен (добавьте {REQUIRED_KEY_VAR} в переменные Railway).',
}


def fetch_coin_news(symbol, limit=5):
    """Fetch fresh, coin-specific news via Google News RSS search (free, no key required)."""
    query = f"{symbol} crypto"
    url = f"https://news.google.com/rss/search?q={quote(query)}&hl=en-US&gl=US&ceid=US:en"
    items = []
    try:
        feed = feedparser.parse(url)
        for entry in feed.entries[:limit]:
            published = entry.get('published_parsed')
            pub_date = datetime(*published[:6]) if published else datetime.utcnow()
            source = ''
            if entry.get('source') and hasattr(entry['source'], 'get'):
                source = entry['source'].get('title', '')
            elif entry.get('source'):
                source = getattr(entry['source'], 'title', '')
            items.append({
                'title': entry.get('title', '').strip(),
                'link': entry.get('link', ''),
                'source': source,
                'published': pub_date,
            })
        items.sort(key=lambda x: x['published'], reverse=True)
    except Exception as e:
        logger.error(f"Coin news fetch error for {symbol}: {e}")
    return items[:limit]


def _build_technical_summary(symbol, timeframe, price, trend_label, scores, patterns, fib_levels, supports, resistances, atr):
    vol = scores.get('volume', {})
    pattern_names = [f"{n} ({'bullish' if n in BULL_PATTERNS else 'bearish' if n in BEAR_PATTERNS else 'neutral'})"
                      for n, _, _ in patterns] or ["none detected"]

    lines = [
        f"Symbol: {symbol}/USDT | Timeframe: {timeframe} | Price: {price:,.6f}",
        f"Trend (EMA-based): {trend_label}",
        f"Signal score: LONG {scores.get('long_score')} vs SHORT {scores.get('short_score')}",
        f"RSI(14): {scores.get('rsi'):.1f}",
        f"MACD: {scores.get('macd'):.6f} | Signal: {scores.get('signal'):.6f} | Histogram: {scores.get('histogram'):.6f}",
        f"Bollinger Bands: upper {scores.get('bb_upper'):,.6f} | mid {scores.get('bb_mid'):,.6f} | lower {scores.get('bb_lower'):,.6f}",
        f"ATR(14): {atr:,.6f}",
        f"Volume: current {vol.get('current_volume', 0):,.0f} ({vol.get('vol_ratio', 1)}x the 20-period average), "
        f"5-candle trend: {vol.get('vol_trend', 'n/a')} ({vol.get('vol_trend_pct', 0):+.1f}%), "
        f"spike: {vol.get('is_spike', False)}, last candle: {'bullish' if vol.get('last_bullish') else 'bearish'}",
        f"Candlestick patterns detected: {', '.join(pattern_names)}",
        f"Nearest support levels: {', '.join(f'{s:,.6f}' for s in supports[:2])}" if supports else "Nearest support levels: none",
        f"Nearest resistance levels: {', '.join(f'{r:,.6f}' for r in resistances[:2])}" if resistances else "Nearest resistance levels: none",
        f"Key Fibonacci levels: " + ", ".join(f"{k}={v:,.6f}" for k, v in fib_levels.items() if k in ('38.2%', '50.0%', '61.8%')),
    ]
    return "\n".join(lines)


def _build_news_summary(news_items, lang):
    if not news_items:
        return NO_NEWS.get(lang, NO_NEWS['en'])
    now = datetime.utcnow()
    lines = []
    for item in news_items:
        hours_ago = max(0, int((now - item['published']).total_seconds() // 3600))
        age_txt = f"{hours_ago}h ago" if hours_ago > 0 else "just now"
        src = f" ({item['source']})" if item['source'] else ""
        lines.append(f"- \"{item['title']}\"{src} — {age_txt}")
    return "\n".join(lines)


def _call_claude(system_prompt, user_content, max_tokens=550, timeout=30):
    if not ANTHROPIC_API_KEY:
        raise RuntimeError("NO_API_KEY")

    headers = {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }
    payload = {
        "model": ANTHROPIC_MODEL,
        "max_tokens": max_tokens,
        "system": system_prompt,
        "messages": [{"role": "user", "content": user_content}],
    }
    resp = requests.post(ANTHROPIC_URL, headers=headers, json=payload, timeout=timeout)
    resp.raise_for_status()
    data = resp.json()
    parts = [b.get('text', '') for b in data.get('content', []) if b.get('type') == 'text']
    return "\n".join(parts).strip()


def _call_gemini(system_prompt, user_content, max_tokens=550, timeout=30):
    if not GEMINI_API_KEY:
        raise RuntimeError("NO_API_KEY")

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"
    payload = {
        "system_instruction": {"parts": [{"text": system_prompt}]},
        "contents": [{"role": "user", "parts": [{"text": user_content}]}],
        "generationConfig": {"maxOutputTokens": max_tokens, "temperature": 0.4},
    }
    resp = requests.post(url, params={"key": GEMINI_API_KEY}, json=payload, timeout=timeout)
    resp.raise_for_status()
    data = resp.json()
    candidates = data.get('candidates') or []
    if not candidates:
        raise RuntimeError("EMPTY_RESPONSE")
    parts = candidates[0].get('content', {}).get('parts', [])
    return "".join(p.get('text', '') for p in parts).strip()


def _call_ai(system_prompt, user_content, max_tokens=550, timeout=30):
    if AI_PROVIDER == "anthropic":
        return _call_claude(system_prompt, user_content, max_tokens, timeout)
    return _call_gemini(system_prompt, user_content, max_tokens, timeout)


def generate_ai_analysis(symbol, timeframe, price, trend_label, scores, patterns,
                          fib_levels, supports, resistances, atr, lang='fa'):
    """Returns (formatted_message, error) — error is None on success."""
    lang_name = LANG_NAMES.get(lang, 'English')

    news_items = fetch_coin_news(symbol, limit=5)
    technical_summary = _build_technical_summary(
        symbol, timeframe, price, trend_label, scores, patterns, fib_levels, supports, resistances, atr
    )
    news_summary = _build_news_summary(news_items, lang)

    system_prompt = (
        f"You are an experienced but cautious crypto market analyst. You will be given "
        f"(1) computed technical indicators for one coin/timeframe and (2) recent real "
        f"news headlines about that coin. Write a concise market commentary in {lang_name} that:\n"
        f"- Synthesizes what the technicals AND the news together suggest, explicitly stating "
        f"whether they agree or conflict with each other\n"
        f"- Names the single most important near-term risk or catalyst visible in the news, if any\n"
        f"- Avoids hype language, avoids exclamation marks, and never gives a direct buy/sell instruction\n"
        f"- Is at most 3 short paragraphs and stays under ~180 words\n"
        f"- Uses plain prose, no headers, no markdown bullet lists\n"
        f"- Do not add any disclaimer yourself, one will be appended separately\n"
        f"Respond only in {lang_name}, with no preamble."
    )
    user_content = (
        f"TECHNICAL DATA:\n{technical_summary}\n\n"
        f"RECENT NEWS ({symbol}):\n{news_summary}\n\n"
        f"Write the analysis now."
    )

    try:
        commentary = _call_ai(system_prompt, user_content)
    except RuntimeError:
        return None, NO_KEY_ERROR.get(lang, NO_KEY_ERROR['en'])
    except requests.exceptions.HTTPError as e:
        logger.error(f"AI analysis HTTP error: {e} | body={getattr(e.response, 'text', '')[:300]}")
        return None, f"API error: {e}"
    except Exception as e:
        logger.error(f"AI analysis error: {e}")
        return None, str(e)

    title = TITLES.get(lang, TITLES['en'])
    disclaimer = DISCLAIMERS.get(lang, DISCLAIMERS['en'])
    message = f"{title}\n\n{commentary}\n\n{disclaimer}"
    return message, None

